const Theme = [
    {
        body: { backgroundColor: "rgb(12, 12, 12)" },
        bodydesc: { backgroundColor: "rgb(12, 12, 12)" },
        profile: { backgroundColor: "#012a4a" },
        bg24: { backgroundColor: "rgb(24, 24, 24)" },
        homeCont: { backgroundColor: "#3B3838" },
        text: { color: "white" },
        textbg: { color: "white", backgroundColor: "rgb(24, 24, 24)" },
        bgtext: { color: "black", backgroundColor: "white" },
        sidedesc: { color: "white", backgroundColor: "rgb(12, 12, 12)" },
        descHover: "bg-gray-700",
        newdescHover: "bg-gray-700",
        newsBox: { backgroundColor: "#3B3838" },
        titlecolor: { color: "#828897" },
        profilEeditBg: { backgroundColor: "#2c7da0" },
        editCourses: { backgroundColor: "rgba(41, 39, 39, 0.8)" },
        editCourseInside: { backgroundColor: "rgb(48, 48, 48)" },
        boxshadow: "0px 0px 15px 4px black",
        boxDown: { backgroundColor: "rgb(23, 22, 22)" },
        textclass: "text-white",
        textbgw: { color: "white", backgroundColor: "rgb(24, 24, 24)" },
    },
    {
        textbgw: { color: "rgb(24, 24, 24)", backgroundColor: "white" },
        boxDown: { backgroundColor: "#d1eaf0" },
        textclass: "text-black",
        body: { backgroundColor: "#e1f4fa" },
        profile: { backgroundColor: "#add8e6" },
        bg24: { backgroundColor: "white" },
        homeCont: { backgroundColor: "#90e0ef" },
        bodydesc: { backgroundColor: "#90e0ef" },
        text: { color: "black" },
        textbg: { color: "rgb(24, 24, 24)", backgroundColor: "#d1eaf0" },
        bgtext: { color: "white", backgroundColor: "rgb(24, 24, 24)" },
        sidedesc: { color: "white", backgroundColor: "#e1f4fa" },
        descHover: "bg-blue-400",
        newdescHover: "bg-gray-700",
        newsBox: { backgroundColor: "#87ceeb" },
        titlecolor: { color: "#828897" },
        profilEeditBg: { backgroundColor: "white" },
        editCourses: { backgroundColor: "rgba(41, 39, 39, 0.8)" },
        editCourseInside: { backgroundColor: "rgb(48, 48, 48)" },

    }
]
export default Theme